# Generated by Django 5.0.1 on 2024-02-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_carinventory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinventory',
            name='cars_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
